wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.10.6
    start_time: 1663121040.4819
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 3
      - 13
      - 16
      - 23
      4: 3.10.6
      5: 0.13.1
      8:
      - 1
      - 2
      - 4
      - 5
architecture:
  desc: null
  value: very-low-cutoff
batch_size:
  desc: null
  value: 2048
context:
  desc: null
  value: 25
epochs:
  desc: null
  value: 3
learning_rate:
  desc: null
  value: 0.001
